import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({

  general_text: {
    fontSize: 15,
    fontWeight: 'bold',
  },

  container: {
    flex: 1,
    width: '100%',
    position: 'relative',
  },

  mask: {
    width: '100%',
    height: '100%',
    backgroundColor: 'rgba(0,0,0,0.18)',
    zIndex: 1,
    position: 'absolute',
    top: 0,
    left: 0,
  },

  post_list: {
    flex: 1,
    width: '100%',
  },

  post_item: {
    width: '100%',
    height: '100%',
  },

  box_friends: {
    width: '100%',
    height: 80,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  toggle_friends: {
    height: 40,
    paddingHorizontal: 16,
    flexDirection: 'row',
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 100,
    elevation: 999,
    borderWidth: 1.5,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
  },
  friends_boad: {
    width: 260,
    maxHeight: 280,
    position: 'absolute',
    top: 60,
    zIndex: 100,
    borderRadius: 18,
    padding: 10,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(254,158,199,0.25)',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
  },
  all_friends: {
    width: '95%',
    paddingBottom: 8,
    marginBottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomColor: 'rgba(159,165,174,0.3)',
    borderBottomWidth: 1,
  },
  friend: {
    width: '100%',
    height: 46,
    flexDirection: 'row',
    alignItems: 'center',
    paddingBottom: 8,
    marginBottom: 8,
    borderBottomColor: 'rgba(159,165,174,0.3)',
    borderBottomWidth: 1,
  },
  gray_circle_border: {
    width: 34,
    height: 34,
    borderRadius: 17,
    borderWidth: 2,
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 6,
  },
  image_area: {
    width: '100%',
    alignItems: 'center',
    paddingHorizontal: 12,
  },
  image: {
    width: '100%',
    borderRadius: 24,
    overflow: 'hidden',
  },
  caption_image: {
    borderRadius: 16,
    paddingVertical: 5,
    paddingHorizontal: 10,
    position: 'absolute',
    bottom: 52,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.45)',
  },
  infoImage: {
    width: '100%',
    height: 52,
    marginTop: 16,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingHorizontal: 12,
  },

  menu_btn_overlay: {
    position: 'absolute',
    top: 10,
    right: 22,
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
  },

  grid_btn: {
    marginLeft: 'auto',
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderWidth: 1.5,
  },

  react_comment_box_hidden: {
    position: 'absolute',
    left: 16,
    right: 16,
    height: 50,
    zIndex: 10,
    borderRadius: 25,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1.5,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 10,
  },
  comment_input: {
    flex: 1,
    height: 40,
    paddingHorizontal: 12,
    fontSize: 15,
    borderRadius: 26,
  },
  send_icon_wrapper: {
    width: 34,
    height: 34,
    borderRadius: 17,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 6,
  },

  action_row: {
    width: '100%',
    height: 56,
    marginTop: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },

  reacted_for_me_box: {
    width: '72%',
    height: 50,
    borderRadius: 25,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 12,
    borderWidth: 1.5,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 4,
  },

  react_comment_box: {
    width: '92%',
    height: 52,
    borderRadius: 26,
    flexDirection: 'row',
    alignItems: 'center',
    paddingRight: 6,
    borderWidth: 1.5,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 4,
  },
  comment: {
    flex: 1,
    height: 40,
    paddingTop: 4,
    paddingBottom: 4,
    paddingLeft: 14,
    justifyContent: 'center',
  },
  emoji_box: {
    width: 38,
    height: 38,
    justifyContent: 'center',
    alignItems: 'center',
  },
  emoji_box_icon: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: 'rgba(26,26,46,0.10)',
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 2,
  },
  emoji: {
    fontSize: 22,
  },

  take_area: {
    width: '100%',
    height: 110,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 60,
    marginTop: 4,
  },
  flash_btn: {
    width: 76,
    height: 76,
    borderRadius: 38,
    justifyContent: 'center',
    alignItems: 'center',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.35,
    shadowRadius: 8,
    elevation: 5,
  },
  flash_btn_inner: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(26,26,46,0.25)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  take_btn: {
    width: 76,
    height: 76,
    borderRadius: 38,
    overflow: 'hidden',
  },
  outerCircle: {
    width: 76,
    height: 76,
    borderRadius: 38,
    borderWidth: 5,
    alignItems: 'center',
    justifyContent: 'center',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.35,
    shadowRadius: 12,
    elevation: 8,
  },
  innerCircle: {
    width: 56,
    height: 56,
    borderRadius: 28,
  },

  reacted_emoji: {
    width: 70,
    height: 70,
    position: 'absolute',
    zIndex: 5,
    bottom: -80,
  },
});
