import { StyleSheet } from "react-native";
import Colors from "../styles/color";
import { scale } from "../utils/scale";

export const styles = StyleSheet.create({
    general_text: {
        color: Colors.white,
        fontSize: 16,
        fontWeight: 'bold',
    },
    container: {
        width: '100%',
        height: '100%',
        backgroundColor: Colors.surface_strong,
        justifyContent: 'center',
        alignItems: 'center',
    },
    send_to: {
        width: '100%',
        height: '10%',
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
    },
    download_btn: {
        position: 'absolute',
        right: 20,
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: Colors.primary,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: Colors.primary,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 4,
    },
    image_area: {
        width: "100%",
        height: "55%",
        paddingTop: 10,
        marginTop: 15,
        paddingHorizontal: 12,
        alignItems: 'center',
    },
    saveImageNoti: {
        width: 150,
        alignItems: 'center',
        padding: 10,
        position: 'absolute',
        top: '45%',
        backgroundColor: Colors.primary,
        borderRadius: 20,
    },
    image: {
        width: '100%',
        height: '88%',
        borderRadius: 60,
        overflow: 'hidden',
    },
    caption_image: {
        maxWidth: '90%',
        borderRadius: 25,
        paddingVertical: 0,
        paddingHorizontal: 10,
        position: 'absolute',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: Colors.black_blur,
    },
    send_btn_area: {
        width: '100%',
        height: '15%',
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
    },
    close_btn: {
        width: 44,
        height: 44,
        borderRadius: 22,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: Colors.primary,
        shadowColor: Colors.primary,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 3,
    },
    send_btn: {
        width: 90,
        height: 90,
        marginLeft: 60,
        marginRight: 60,
        paddingRight: 5,
        paddingTop: 5,
        borderRadius: 50,
        backgroundColor: Colors.primary,
        overflow: 'hidden',
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: Colors.primary,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.5,
        shadowRadius: 8,
        elevation: 6,
    },
    friend_list: {
        height: '20%',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
    },
    friend: {
        width: 70,
        height: 70,
        flexDirection: 'column',
        alignItems: 'center',
        marginRight: 10,
    },
    gray_circle_border: {
        width: 35,
        height: 35,
        borderRadius: 999,
        borderWidth: 3,
        borderColor: Colors.primary,
        overflow: 'hidden',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 10,
    },
    caption_pattern: {
        position: 'absolute',
        bottom: 0,
        width: '100%',
        height: 300,
        backgroundColor: Colors.neutral_dark2,
        borderTopEndRadius: 40,
        borderTopStartRadius: 40,
        alignItems: 'center',
        borderTopWidth: 1,
        borderColor: Colors.primary,
    },
    loadingOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0,0,0,0.25)',
        justifyContent: 'center',
        alignItems: 'center',
        transform: [{ scale: 2.5 }],
        zIndex: 999,
    },
    mask: {
        width: '100%',
        height: '100%',
        backgroundColor: Colors.black_blur,
        position: 'absolute',
    },
    general: {
        width: '100%',
        height: '25%',
        paddingStart: 20,
    },
    decorative: {
        width: '100%',
        height: '45%',
        paddingStart: 20,
    },
    box_radius: {
        height: 40,
        backgroundColor: Colors.neutral_dark3,
        padding: 8,
        paddingEnd: 10,
        paddingStart: 10,
        borderRadius: 18,
        marginEnd: 20,
        marginBottom: 8,
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: Colors.secondary,
    },
    box_area: {
        width: '100%',
        flexDirection: 'row',
        flexWrap: 'wrap',
        marginTop: 8,
    },
    text_caption: {
        fontWeight: "800",
        color: Colors.text_primary,
        fontSize: 15,
    },
});