import { Dimensions, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  general_text: {
    fontSize: 14,
    fontWeight: 'bold',
  },
  container: {
    height: Dimensions.get('window').height,
    flex: 1,
    backgroundColor: 'transparent',
  },
  toggle_friends: {
    width: "100%",
    height: "10%",
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  gray_circle_border: {
    width: '100%',
    height: '100%',
    borderRadius: 999,
    borderWidth: 3,
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
  },
  box_friends: {
    width: 150,
    height: 50,
    flexDirection: 'row',
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 10,
    marginLeft: 50,
    marginRight: 40,
    borderWidth: 1,
  },
  camera_area: {
    width: "100%",
    height: "70%",
    paddingTop: 10,
    paddingHorizontal: 12,
  },
  camera: {
    width: '100%',
    height: '75%',
    borderRadius: 24,
    overflow: 'hidden',
  },
  take_area: {
    width: '100%',
    height: '40%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  flash_btn: {
    width: 60,
    height: 60,
    borderRadius: 999,
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
  },
  take_btn: {
    width: 100,
    height: 100,
    marginLeft: 50,
    marginRight: 50,
    borderRadius: 50,
    overflow: 'hidden',
  },
  outerCircle: {
    width: 100,
    height: 100,
    borderRadius: 50,
    borderWidth: 6,
    alignItems: 'center',
    justifyContent: 'center',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.35,
    shadowRadius: 12,
    elevation: 8,
  },
  innerCircle: {
    width: 75,
    height: 75,
    borderRadius: 35,
  },
  history: {
    width: "100%",
    height: "30%",
    alignItems: 'center',
    marginTop: 50,
  },
});