import { StyleSheet } from 'react-native';
import Colors from "../styles/color";

export const styles = StyleSheet.create({
  container: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 0,    // Đã có View padding bên ngoài
    paddingBottom: 12,
    width: '100%',
    zIndex: 10,
    backgroundColor: 'transparent', 
  },

  iconButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  avatarImage: {
    width: 40,
    height: 40,
    borderRadius: 20,
  },
  iconImage: {
    width: 26,
    height: 26,
    tintColor: Colors.text_secondary,
  },

  filterButton: {
    height: 44,
    paddingHorizontal: 18,
    borderRadius: 22,
    borderWidth: 1.5,
    borderColor: Colors.primary,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.surface_strong,
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 2,
  },
  title: {
    color: Colors.text_primary,
    fontSize: 15,
    fontWeight: '600',
    marginRight: 6,
    maxWidth: 140,
  },
  arrowDown: {
    width: 0,
    height: 0,
    backgroundColor: 'transparent',
    borderStyle: 'solid',
    borderLeftWidth: 5,
    borderRightWidth: 5,
    borderTopWidth: 7,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderTopColor: Colors.text_secondary,
  },

  homeFriendsButton: {
    height: 44,
    paddingHorizontal: 18,
    borderRadius: 22,
    backgroundColor: Colors.surface_strong,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: Colors.primary,
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 2,
  },
  box_friends: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  homeTextCount: {
    paddingLeft: 8,
    color: Colors.text_primary,
    fontSize: 15,
    fontWeight: '700',
  },
  homeTextLabel: {
    paddingLeft: 4,
    fontWeight: '600',
    color: Colors.text_secondary,
    fontSize: 15,
  },

  mask: {
    flex: 1,
    backgroundColor: 'rgba(26,26,46,0.35)',
    alignItems: 'center',
    paddingTop: 110,
  },
  dropdownBoard: {
    width: 280,
    backgroundColor: Colors.surface_strong,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(254,158,199,0.25)',
    overflow: 'hidden',
    height: 300,
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
    elevation: 8,
  },
  separator: {
    height: 1,
    backgroundColor: 'rgba(159,165,174,0.25)',
  },
});
