require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, min_ios_version_supported
prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { android: { sourceDir: '../node_modules/react-native-flipper/android', packageImportPath: 'io.invertase.flipper' } } } } : {}),
#   },
# };
# ```

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'Modis' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )



  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
    
    # Fix for Xcode 15+ compatibility and cloud builds
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # Set minimum iOS deployment target
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'
        
        # Fix for fmt library compilation with Xcode 26.4 beta
        if target.name.include?('fmt') || target.name.include?('Fmt') || target.name.include?('Folly') || target.name.include?('glog')
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'FMT_CONSTEVAL='
          # Additional C++ compiler flags for fmt compatibility
          config.build_settings['OTHER_CPLUSPLUSFLAGS'] ||= ['$(inherited)']
          config.build_settings['OTHER_CPLUSPLUSFLAGS'] << '-DFMT_CONSTEVAL='
        end
        
        # Fix for react-native-vision-camera
        if target.name == 'VisionCamera'
          config.build_settings['SWIFT_VERSION'] = '5.0'
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'VISION_CAMERA_ENABLE_FRAME_PROCESSORS=1'
        end
        
        # Fix for Reanimated
        if target.name.start_with?('RNReanimated')
          config.build_settings['SWIFT_VERSION'] = '5.0'
        end
        
        # Fix for react-native-worklets
        if target.name.include?('worklets')
          config.build_settings['SWIFT_VERSION'] = '5.0'
        end
        
        # Fix for AsyncStorage
        if target.name == 'RNCAsyncStorage'
          config.build_settings['SWIFT_VERSION'] = '5.0'
        end
        
        # Fix for gesture-handler
        if target.name == 'RNGestureHandler'
          config.build_settings['SWIFT_VERSION'] = '5.0'
        end
        
        # Fix for vector-icons
        if target.name == 'RNVectorIcons'
          config.build_settings['SWIFT_VERSION'] = '5.0'
        end
        
        # General iOS 15.1+ compatibility fixes
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64' if config.name == 'Debug'
        
        # Code signing for unsigned builds
        if ENV['CODE_SIGNING_REQUIRED'] == 'NO'
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
          config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
        end
        
        # Disable bitcode (deprecated in Xcode 14+)
        config.build_settings['ENABLE_BITCODE'] = 'NO'
        
        # Optimize for cloud builds
        config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO' if config.name == 'Release'
        config.build_settings['VALID_ARCHS'] = 'arm64'
        
        # Fix potential linker issues
        config.build_settings['LIBRARY_SEARCH_PATHS'] ||= ['$(inherited)']
        config.build_settings['LIBRARY_SEARCH_PATHS'] << '"$(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME)"'
      end
    end
    
    # Fix for iOS 15.1+ and Xcode 15+ compatibility
    installer.pods_project.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'
    end
  end
end